### PR TITLE
fix(a2d): Qwen2/3 forward use layer_types[i] (transformers>=4.57)

### LINKED ISSUE #262: fix(a2d): Qwen2/Qwen3 A2D forward breaks on transformers>=4.57 (attention_type vs layer_types)
## Summary

Four tests in `tests/models/test_a2d.py` fail on current stacks (e.g. `transformers==4.57.6`) with:

```
AttributeError: 'Qwen2DecoderLayer' object has no attribute 'attention_type'
```
(same for `Qwen3DecoderLayer`).

## Root cause

Unturtle`s forked `A2DQwen2Model` / `A2DQwen3Model` (`unturtle/models/a2d/modeling_qwen2.py`, `modeling_qwen3.py`) still indexed the prepared mask map with `decoder_layer.attention_type`.

Upstream **Hugging Face `transformers` (~4.57)** changed `Qwen2Model.forward` / `Qwen3Model.forward` to use **`self.config.layer_types[i]`** per layer instead of an attribute on the decoder layer (see `transformers/models/qwen2/modeling_qwen2.py` around the layer loop, and the analogous Qwen3 file).

`Qwen2Config` / `Qwen3Config` now populate `layer_types` in `__post_init__` when unset, so the correct lookup is `causal_mask_mapping[self.config.layer_types[i]]`.

## Why it used to pass

Older `transformers` exposed `attention_type` on decoder layers (or Unturtle was tested against an older pin). After upgrading the training / Studio pin to 4.57.x, the layer class no longer carries that attribute.

## Fix

Align A2D Qwen2/Qwen3 model `forward` with upstream: `enumerate(self.layers)` and `causal_mask_mapping[self.config.layer_types[i]]`.

## Repro

```bash
.venv/bin/pytest tests/models/test_a2d.py::TestA2DQwen2::test_forward_logits_shape -vv
```

(Used to fail before the forward-loop change; passes after.)

### PR DESCRIPTION
**Pull request by nishide-dev**
## Problem
Tests in `tests/models/test_a2d.py` failed with `'Qwen2DecoderLayer' object has no attribute 'attention_type'` on current `transformers` (see #262).

## Change
- `modeling_qwen2.py` / `modeling_qwen3.py`: select `causal_mask_mapping` with `self.config.layer_types[i]` and `enumerate(self.layers)`, matching upstream `Qwen2Model` / `Qwen3Model`.

## Verification
```bash
.venv/bin/pytest tests/models/test_a2d.py::TestA2DQwen2::test_forward_logits_shape \
  tests/models/test_a2d.py::TestA2DQwen3::test_forward_logits_shape \
  tests/models/test_a2d.py::TestA2DBidirectional::test_attends_to_future_tokens -q
```
(5 passed)

Fixes #262.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by nishide-dev** [comment]
## PR review (automated + `tests/models/test_a2d.py`)

**Critical / important:** なし。HF upstream の `config.layer_types[i]` 選択と整合し、従来の dict 渡し時の KeyError 契約も変わらない。

**Tests:** `.venv/bin/pytest tests/models/test_a2d.py` → **60 passed**, 1 skipped。

**Suggestion（任意）:** `attention_mask` の型ヒントが `Tensor | None` のままだが実装は dict も受け取る — 型だけの改善でマージは不要。
